from playwright.sync_api import sync_playwright

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<style>
  body {{
    font-family: 'Inter', sans-serif;
    background-color: #f5f6f9;
    padding: 40px;
    margin: 0;
    width: 1200px;
    height: 630px;
    box-sizing: border-box;
    display: flex;
    flex-direction: column;
    justify-content: center;
  }}
  .card {{
    background: white;
    border-radius: 24px;
    padding: 40px;
    box-shadow: 0 10px 30px rgba(0,0,0,0.1);
    display: flex;
    flex-direction: column;
    height: 100%;
    border-top: 10px solid #003CBD;
  }}
  h1 {{ color: #1E3A8A; font-size: 36px; margin-top: 0; }}
  .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 30px; margin-top: 20px; }}
  .box {{ background: #EBF2FF; padding: 20px; border-radius: 12px; }}
  .box h2 {{ color: #003CBD; margin-top: 0; font-size: 20px; }}
  .box p {{ font-size: 24px; font-weight: bold; color: #18181b; margin: 10px 0 0 0; }}
  .success {{ background: #EBF7F2; border-left: 5px solid #19C480; }}
  .success h2 {{ color: #0A7C5C; }}
  .footer {{ margin-top: auto; color: #71717a; font-size: 14px; text-align: right; }}
</style>
</head>
<body>
  <div class="card">
    <h1>{title}</h1>
    <div class="grid">
      <div class="box">
        <h2>Population</h2>
        <p>{population}</p>
      </div>
      <div class="box">
        <h2>Intervention vs Comparison</h2>
        <p>{intervention} vs {comparison}</p>
      </div>
      <div class="box success" style="grid-column: span 2;">
        <h2>Primary Outcome</h2>
        <p>{outcome} ({stats})</p>
      </div>
    </div>
    <div class="footer">Generated by Context-Med (Mock)</div>
  </div>
</body>
</html>
"""

def render_visual_abstract(data: dict, output_path: str):
    html_content = HTML_TEMPLATE.format(
        title=data["title"],
        population=data["pico"]["population"],
        intervention=data["pico"]["intervention"],
        comparison=data["pico"]["comparison"],
        outcome=data["pico"]["outcome"],
        stats=data["stats"],
    )
    
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page(viewport={"width": 1200, "height": 630})
        page.set_content(html_content)
        page.wait_for_timeout(200)
        page.screenshot(path=output_path)
        browser.close()
